[package]
name = "syncra-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30"
ash = "0.38"
metal = "0.30"
d3d12 = "22.0"
openxr = "0.11"
windows = "0.58"
coreaudio-sys = "0.2"
alsa-sys = "0.3"