[workspace]

members = [
    "syncra-client",
    "syncra-server",
    "syncra-asset-server",
    "syncra-audio",
    "syncra-input",
    "syncra-openxr",
    "syncra-renderer",
    "syncra-windowing"
]
