/* automatically generated by rust-bindgen 0.70.1 */

pub const CGLM_HAVE_BUILTIN_ASSUME_ALIGNED: u32 = 1;
pub const CGLM_SSE_FP: u32 = 1;
pub const CGLM_SSE2_FP: u32 = 1;
pub const CGLM_CLIP_CONTROL_ZO_BIT: u32 = 1;
pub const CGLM_CLIP_CONTROL_NO_BIT: u32 = 2;
pub const CGLM_CLIP_CONTROL_LH_BIT: u32 = 4;
pub const CGLM_CLIP_CONTROL_RH_BIT: u32 = 8;
pub const CGLM_CLIP_CONTROL_LH_ZO: u32 = 5;
pub const CGLM_CLIP_CONTROL_LH_NO: u32 = 6;
pub const CGLM_CLIP_CONTROL_RH_ZO: u32 = 9;
pub const CGLM_CLIP_CONTROL_RH_NO: u32 = 10;
pub const CGLM_CONFIG_CLIP_CONTROL: u32 = 10;
pub const CGLM_PRINT_PRECISION: u32 = 5;
pub const CGLM_PRINT_MAX_TO_SHORT: f64 = 100000.0;
pub const CGLM_PRINT_COLOR: &[u8; 6] = b"\x1B[36m\0";
pub const CGLM_PRINT_COLOR_RESET: &[u8; 5] = b"\x1B[0m\0";
pub const CGLM_DECASTEL_EPS: f64 = 0.000000001;
pub const CGLM_DECASTEL_MAX: u32 = 1000;
pub const CGLM_DECASTEL_SMALL: f64 = 0.00000000000000000001;
