[package]
name = "SyncraOS"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "23.0.1"
glfw = "0.59.0"
winit = "0.30.5"
ash = { version="0.38.0", features = ["linked"] }
openxr = "0.19.0"
raw-window-handle = "0.6.2"
pollster = "0.4.0"
env_logger = "0.11.5"