[package]
name = "syncra-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "23.0"
winit = "0.30"
log = "0.4"
env_logger = "0.11"
bevy_ecs = "0.14"
pollster = "0.4"
nalgebra = "0.33"
bevy_asset = "0.14"