[package]
name = "SyncraOS"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { version = "0.38.0+1.3.281", features = ["linked"] }
ash-window = "0.13.0"
openxr = "0.19.0"
glfw = "0.59.0"
raw-window-handle = "0.6.2"